# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdeb30df11fc1ba8d12151ca20ba34e85677e774264ed17956893cf93a543928a770f487daded2be7e1cf65de93bb130133af86a843598d81523058873b9202d

test:
  secret_key_base: e85a55119885f79cbb776d05e48f773ebb3c6ac4691c12dcccf4b03c5d2386faa39050e251fe3be05e88dde794b9cbd0555038b6ec7b1de10e54f13db12b4d96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
